### ISSUE TITLE
error playing next track

### ISSUE THREAD

**Issue by jfalxa** [internet4000/r4#5]
when using `r4 play 200ok`, after the end of the first track, there is an error while trying to play the second track.

```
~/Music $ r4 play 200ok
Listening to Scuba - Three Sided Shape from 200ok.
(node:35821) UnhandledPromiseRejectionWarning: Error: Input stream error: write after end
    at DuplexWrapper.<anonymous> (/Users/falxa/.nvm/versions/node/v10.11.0/lib/node_modules/r4/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at DuplexWrapper.emit (events.js:182:13)
    at PassThrough.<anonymous> (/Users/falxa/.nvm/versions/node/v10.11.0/lib/node_modules/r4/node_modules/duplexer3/index.js:49:12)
    at PassThrough.emit (events.js:187:15)
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:291:5)
    at IncomingMessage.ondata (_stream_readable.js:666:20)
    at IncomingMessage.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
(node:35821) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35821) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Illegal instruction: 4
```

**Comment by oskarrough** [comment]
Yes! We actually haven't implemented continuous play yet.. 

All we have is here:

https://github.com/internet4000/r4/blob/5ce25ba7c0914255201e52df21601a770f297a1b/r4-play.js#L29-L38

**Comment by oskarrough** [comment]
Two possible solutions:

a) listen for some "track ended" event and play next track, stop if no next track
b) adjust the console.log so people really know it's just a preview for now

@jfalxa do you feel like one of them?

**Comment by hugurp** [comment]
Maybe then it is good not to have the `play` command in the CLI?

**Comment by hugurp** [comment]
fixed because this app does no more playing but management of files and folders
